from app.database import SessionLocal, engine
from app.models import Base, Car

Base.metadata.create_all(bind=engine)

data_list = [
    { "number": 1, "car_id": "RDE35999", "zone": "C", "zone_number": None },
    { "number": 2, "car_id": "RDEH5", "zone": "C", "zone_number": None },
    { "number": 3, "car_id": "RKL24356", "zone": "D", "zone_number": None },
    { "number": 4, "car_id": "RKL24356", "zone": "D", "zone_number": None },
    { "number": 6, "car_id": "KBC61WF", "zone": "C", "zone_number": None },
    { "number": 7, "car_id": "RZ8489V", "zone": "B", "zone_number": None },
    { "number": 8, "car_id": "RDE85930", "zone": "C", "zone_number": None },
    { "number": 9, "car_id": "RRS44420", "zone": "B", "zone_number": None },
    { "number": 10, "car_id": "KTA74083", "zone": "C", "zone_number": None },
    { "number": 11, "car_id": "RJSSN53", "zone": "D", "zone_number": None },
    { "number": 12, "car_id": "OGLFM63", "zone": "C", "zone_number": None },
    { "number": 13, "car_id": "KBC23VG", "zone": "C", "zone_number": None },
    { "number": 14, "car_id": "RDE20705", "zone": "B", "zone_number": None },
    { "number": 15, "car_id": "KBC28S7", "zone": "C", "zone_number": None },
    { "number": 16, "car_id": "R3YR", "zone": "A", "zone_number": None },
    { "number": 17, "car_id": "KAVCARS", "zone": "A", "zone_number": None },
    { "number": 18, "car_id": "RDE58823", "zone": "C", "zone_number": None },
    { "number": 20, "car_id": "RST38596", "zone": "C", "zone_number": None },
    { "number": 21, "car_id": "RKL84XC", "zone": "D", "zone_number": None },
    { "number": 22, "car_id": "RKR39867", "zone": "C", "zone_number": None },
    { "number": 23, "car_id": "RDE65095", "zone": "C", "zone_number": None },
    { "number": 24, "car_id": "RPR52859", "zone": "D", "zone_number": None },
    { "number": 25, "car_id": "RZ434CF", "zone": "D", "zone_number": None },
    { "number": 26, "car_id": "RDE44217", "zone": "D", "zone_number": None },
    { "number": 27, "car_id": "KTA4646J", "zone": "C", "zone_number": None },
    { "number": 28, "car_id": "KGRKM31", "zone": "C", "zone_number": None },
    { "number": 29, "car_id": "87109", "zone": "C", "zone_number": None },
    { "number": 30, "car_id": "R1WV", "zone": "B", "zone_number": None },
    { "number": 31, "car_id": "RDE92242", "zone": "C", "zone_number": None },
    { "number": 32, "car_id": "OLIMP RACING", "zone": "A", "zone_number": None },
    { "number": 33, "car_id": "OLIMP RACING", "zone": "A", "zone_number": None },
    { "number": 34, "car_id": "KAVCARS", "zone": "A", "zone_number": None },
    { "number": 35, "car_id": "RTA41880", "zone": "C", "zone_number": None },
    { "number": 36, "car_id": "OLIMP RACING", "zone": "A", "zone_number": None },
    { "number": 37, "car_id": "OLIMP RACING", "zone": "A", "zone_number": None },
    { "number": 38, "car_id": "RDE77992", "zone": "A", "zone_number": None },
    { "number": 39, "car_id": "OLIMP RACING", "zone": "A", "zone_number": None },
    { "number": 40, "car_id": "RDE60703", "zone": "D", "zone_number": None },
    { "number": 41, "car_id": "RZ584AV", "zone": "D", "zone_number": None },
    { "number": 42, "car_id": "RZ070FF", "zone": "D", "zone_number": None },
    { "number": 43, "car_id": "RZ070FF AC Cobra ZR GARAGE", "zone": "D", "zone_number": None },
    { "number": 44, "car_id": "RDE47476", "zone": "", "zone_number": None },
    { "number": 45, "car_id": "Focus ST", "zone": "D", "zone_number": None },
    { "number": 46, "car_id": "mercedes c63", "zone": "D", "zone_number": None },
    { "number": 47, "car_id": "mercedes g63", "zone": "D", "zone_number": None },
    { "number": 48, "car_id": "FERRARI F12", "zone": "D", "zone_number": None },
    { "number": 49, "car_id": "GR", "zone": "C", "zone_number": None },
    { "number": 50, "car_id": "S13 SILVIA", "zone": "C", "zone_number": None },
    { "number": 51, "car_id": "JUGOWSKI", "zone": "C", "zone_number": None },
    { "number": 52, "car_id": "DUDA", "zone": "C", "zone_number": None },
    { "number": 53, "car_id": "DUDA", "zone": "C", "zone_number": None },
    { "number": 54, "car_id": "R5RIDE5", "zone": "D", "zone_number": None },
    { "number": 55, "car_id": "RPRU407", "zone": "D", "zone_number": None },
    { "number": 56, "car_id": "KR2RY97", "zone": "B", "zone_number": None },
    { "number": 57, "car_id": "R9GTI", "zone": "D", "zone_number": None },
    { "number": 58, "car_id": "RDE36352", "zone": "C", "zone_number": None },
    { "number": 59, "car_id": "RDE84344", "zone": "B", "zone_number": None },
    { "number": 60, "car_id": "RBR22072", "zone": "C", "zone_number": None },
    { "number": 61, "car_id": "R7XVXVX", "zone": "D", "zone_number": None },
    { "number": 62, "car_id": "RBI35AH", "zone": "C", "zone_number": None },
    { "number": 63, "car_id": "RRS36363", "zone": "D", "zone_number": None },
    { "number": 64, "car_id": "K1BOREK", "zone": "D", "zone_number": None },
    { "number": 65, "car_id": "KBC70WF", "zone": "C", "zone_number": None },
    { "number": 66, "car_id": "RAH6", "zone": "A", "zone_number": None },
    { "number": 67, "car_id": "KBC", "zone": "C", "zone_number": None },
    { "number": 68, "car_id": "dodge demon170", "zone": "A", "zone_number": None },
    { "number": 69, "car_id": "Corvette", "zone": "A", "zone_number": None },
    { "number": 70, "car_id": "CLS63 AMG", "zone": "A", "zone_number": None },
    { "number": 71, "car_id": "RAM 1500", "zone": "A", "zone_number": None },
    { "number": 72, "car_id": "S8", "zone": "A", "zone_number": None },
    { "number": 73, "car_id": "WRANGLER", "zone": "A", "zone_number": None },
    { "number": 75, "car_id": "RAK6 Dodge Charger", "zone": "C", "zone_number": None },
    { "number": 76, "car_id": "KLI34364", "zone": "C", "zone_number": None },
    { "number": 77, "car_id": "Nissan 370z biały", "zone": "C", "zone_number": None },
    { "number": 78, "car_id": "RDEJY02", "zone": "C", "zone_number": None },
    { "number": 79, "car_id": "REJKE6A", "zone": "D", "zone_number": None },
    { "number": 80, "car_id": "RDE53600", "zone": "D", "zone_number": None },
    { "number": 81, "car_id": "R1C4 Dodge ChalLenger", "zone": "C", "zone_number": None },
    { "number": 82, "car_id": "RDE16908", "zone": "D", "zone_number": None },
    { "number": 83, "car_id": "RDE89191", "zone": "D", "zone_number": None },
    { "number": 84, "car_id": "R7RCZ", "zone": "D", "zone_number": None },
    { "number": 85, "car_id": "RDE82875", "zone": "D", "zone_number": None },
    { "number": 86, "car_id": "RDE84944", "zone": "D", "zone_number": None },
    { "number": 87, "car_id": "RBR19SA", "zone": "D", "zone_number": None },
    { "number": 88, "car_id": "R4NF", "zone": "A", "zone_number": None },
    { "number": 89, "car_id": "Fiat 125p", "zone": "C", "zone_number": None },
    { "number": 100, "car_id": "Nissan Gtr R33", "zone": "A", "zone_number": None },
    { "number": 101, "car_id": "KLI34364", "zone": "B", "zone_number": None },
    { "number": 102, "car_id": "RC02", "zone": "A", "zone_number": None },
    { "number": 103, "car_id": "K0RDUDI", "zone": "D", "zone_number": None },
    { "number": 104, "car_id": "KFX6", "zone": "D", "zone_number": None },
    { "number": 105, "car_id": "MERC BECZKA", "zone": "D", "zone_number": None },
    { "number": 106, "car_id": "WLS29772", "zone": "D", "zone_number": None },
    { "number": 107, "car_id": "RDE35883", "zone": "D", "zone_number": None },
    { "number": 108, "car_id": "RZ41H", "zone": "D", "zone_number": None },
    { "number": 109, "car_id": "R4F5", "zone": "A", "zone_number": None },
    { "number": 110, "car_id": "dodge viper", "zone": "A", "zone_number": None },
    { "number": 111, "car_id": "mercedes amg gtr pro", "zone": "A", "zone_number": None },
    { "number": 113, "car_id": "WML30587 zr GARAGE", "zone": "D", "zone_number": None },
    { "number": 114, "car_id": "bmw m240i zr GARAGE", "zone": "D", "zone_number": None },
    { "number": 115, "car_id": "Camaro ZL1 FENRIS", "zone": "", "zone_number": None },
    { "number": 116, "car_id": "BMW E46 Driftcar FENRIS", "zone": "", "zone_number": None },
    { "number": 117, "car_id": "Dodge Challenger FENRIS", "zone": "", "zone_number": None },
    { "number": 118, "car_id": "Mustang FORD FENRIS", "zone": "", "zone_number": None },
    { "number": 119, "car_id": "ZŁomek", "zone": "C", "zone_number": None },
    { "number": 120, "car_id": "Dariusz Szybisty Mercedes", "zone": "C", "zone_number": None },
    { "number": 121, "car_id": "RAM TRX LUNAR EVO CARS M2 QBI", "zone": "", "zone_number": None },
    { "number": 122, "car_id": "MB SL63 EVO CARS", "zone": "", "zone_number": None },
    { "number": 123, "car_id": "M4 EVO CARS", "zone": "", "zone_number": None },
    { "number": 124, "car_id": "M2 MANHART EVO CARS", "zone": "", "zone_number": None },
    { "number": 125, "car_id": "LAMBO URUS EVO CARS", "zone": "", "zone_number": None },
    { "number": 126, "car_id": "MH2 EVO CARS", "zone": "", "zone_number": None },
    { "number": 127, "car_id": "GT63S MANSORY EVO CARS", "zone": "", "zone_number": None },
    { "number": 128, "car_id": "BMW 740D EVO CARS", "zone": "", "zone_number": None },
    { "number": 129, "car_id": "BMW 7", "zone": "", "zone_number": None },
    { "number": 130, "car_id": "HUMMER", "zone": "", "zone_number": None },
    { "number": 131, "car_id": "RA06", "zone": "C", "zone_number": None },
    { "number": 132, "car_id": "DAREK RS6", "zone": "A", "zone_number": None },
    { "number": 133, "car_id": "RA90", "zone": "A", "zone_number": None },
    { "number": 134, "car_id": "R2STI", "zone": "C", "zone_number": None },
    { "number": 135, "car_id": "K8WM", "zone": "A", "zone_number": None },
    { "number": 136, "car_id": "K1C63", "zone": "A", "zone_number": None },
    { "number": 137, "car_id": "RRS16000", "zone": "C", "zone_number": None },
    { "number": 138, "car_id": "SXX1", "zone": "A", "zone_number": None },
    { "number": 140, "car_id": "RDE76294", "zone": "D", "zone_number": None },
    { "number": 141, "car_id": "WRAK RACE MACHINE", "zone": "B", "zone_number": None },
    { "number": 142, "car_id": "WRAK RACE MACHINE", "zone": "B", "zone_number": None },
    { "number": 143, "car_id": "RTA39419", "zone": "C", "zone_number": None },
    { "number": 144, "car_id": "BMW650i", "zone": "A", "zone_number": None },
    { "number": 145, "car_id": "Dodge RAM", "zone": "A", "zone_number": None },
    { "number": 146, "car_id": "RAL6 Dodge Chalenger", "zone": "C", "zone_number": None },
    { "number": 147, "car_id": "RDE87700", "zone": "B", "zone_number": None },
    { "number": 148, "car_id": "RAM7", "zone": "C", "zone_number": None },
    { "number": 149, "car_id": "", "zone": "A", "zone_number": None },
    { "number": 150, "car_id": "BMW M5 E39", "zone": "D", "zone_number": None },
    { "number": 151, "car_id": "", "zone": "", "zone_number": None },
    { "number": 152, "car_id": "fioletowy golf air ride", "zone": "C", "zone_number": None },
    { "number": 153, "car_id": "R8YV Dodge ChalLenger", "zone": "C", "zone_number": None },
    { "number": 154, "car_id": "BRZ ROCKET BUNNY", "zone": "A", "zone_number": None },
    { "number": 155, "car_id": "RLA35699", "zone": "D", "zone_number": None },
    { "number": 156, "car_id": "KAVCARS", "zone": "A", "zone_number": None },
    { "number": 158, "car_id": "Igor Maciechowski ZABYTEK", "zone": "D", "zone_number": None },
    { "number": 159, "car_id": "Audi RS3 FENRIS", "zone": "D", "zone_number": None },
    { "number": 160, "car_id": "corvette c8 2020 FENRIS", "zone": "D", "zone_number": None },
    { "number": 161, "car_id": "Mitsubishi EVO ELBAS", "zone": "D", "zone_number": None },
    { "number": 162, "car_id": "Corvette c8 ELBAS", "zone": "D", "zone_number": None },
    { "number": 163, "car_id": "Corvette c8 ELBAS", "zone": "D", "zone_number": None },
    { "number": 164, "car_id": "RAM XXX EVO CARS", "zone": "C", "zone_number": None },
    { "number": 166, "car_id": "BMW 1 230i F22", "zone": "", "zone_number": None },
]

db = SessionLocal()

for entry in data_list:
    car = Car(
        number=entry["number"],
        car_id=entry["car_id"],
        zone=entry["zone"],
        zone_number=entry["zone_number"]
    )
    db.add(car)

db.commit()
db.close()

print("✅ Dane załadowane do bazy danych.")
